version: '3.8'

services:

  db:
    image: postgres
    restart: always
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev

  redis:
    image: redis
    restart: always
    container_name: redis_app
    command: -p 5436
    expose:
      - 5436


  api:
    restart: always
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app

    command:
      - bash -c " uvicorn src.app:app --reload
    ports:
      - 8001:8000
    depends_on:
      - db_app
      - redis_app



